// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventoApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240921000002_VersaoMySQL")]
    partial class VersaoMySQL
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Ingresso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NomeEvento")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeParticipante")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Ingresso");
                });
#pragma warning restore 612, 618
        }
    }
}
